version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    groups:
      production-minor-and-patch:
        applies-to: version-updates
        dependency-type: production
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        applies-to: version-updates
        dependency-type: development
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
